version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /var/www/html
    env_file: 
      - sovocal-testing.env
    command: rails s