# ALL THE CRON JOBS WHICH HAS TO BE SCHEDULED VIA SIDEKIQ GOES HERE


trail_calculation_and_update_cron:
  cron: "0 0 * * *"
  class: "TrailCalculationAndUpdateJob"
  queue: default

billing_calculation_cron:
  cron: "0 0 * * *"
  class: "BillingCalculationsJob"
  queue: default

post_user_engagement_cron:
  cron: "0 */2 * * *"
  class: "PostUserEngagementJob"
  queue: default
